### ISSUE TITLE
Error when running command 

### ISSUE THREAD

**Issue by caseyrlentz** [codeinthedark/editor#7]
I've tried to get the editor to run but I keep running into an error in the terminal. 
<code> ERROR in `libsass` bindings not found. Try reinstalling `node-sass`?
 @ ./app/styles/index.scss 4:14-276 11:1-15:3 12:19-281
</code>
Can someone please help out. Its my wish to get a code in the dark setup in southern California. 
cheers

**Comment by LuaxY** [comment]
I have the same error, on linux and windows.

**Comment by lun471k** [comment]
Have you guys tried manually installing Atom's `node-sass` package?

**Comment by LuaxY** [comment]
Yes, didn't work

**Comment by alexgleason** [comment]
This is a common problem affecting a number of packages. I don't remember which was which, but an update to either Node or to node-sass broke support for previous versions of the other.

It's caused by the version of Node on your system vs the version of node-sass that's running.

It looks like the version of sass-loader in package.json is using a very outdated version of node-sass. Updating this dependency fixes the problem for me. See my PR #9
